### ISSUE TITLE
Schnittstelle zum Erstellen eines neuen Sportfests

### ISSUE THREAD

**Issue by JonasxRie** [atiw-sportfest/backend#28]
Es wird noch ein REST Schnittstelle benötigt mit der ein neues Sportfest angelegt werden kann. Also die Datenbank einmal geleert wird. Evtl. mit Ausnahme der User Daten

**Comment by criztovyl** [comment]
Vllt `DELETE /`?

**Comment by criztovyl** [comment]
atiw-sportfest/atiw-sportfest#3

*Edit, 3 nicht 2.*
