### ISSUE TITLE
UserResource

### ISSUE THREAD

**Issue by criztovyl** [atiw-sportfest/backend#4]
- [x] `GET /user/login`
- [x] `GET /user/privileges`
- [x] `POST /user/privileges`
- [x] `GET /user`
- [x] `POST /user`
- [x] `DELETE /user/{uid}`
- [x] DTO

**Comment by criztovyl** [comment]
Auch noch `POST /user/privileges`.

**Comment by criztovyl** [comment]
`POST /user/login` Rollen scheinen nicht zu funktionieren.

**Comment by T0BiD** [comment]
done
